// Fill out your copyright notice in the Description page of Project Settings.

#include "CppHubActor.h"
#include "TimerManager.h"
#include "MyActor.h"

// Sets default values
ACppHubActor::ACppHubActor()
{
    // Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
    PrimaryActorTick.bCanEverTick = true;
}

// Called when the game starts or when spawned
void ACppHubActor::BeginPlay()
{
    Super::BeginPlay();
    GetWorldTimerManager().SetTimer(SpawnTimerHandle, this, &ACppHubActor::onTimeToSpawn, SpawnTimerRate, true);
}

// Called every frame
void ACppHubActor::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);
}

void ACppHubActor::onTimeToSpawn()
{
    if (++CurrentTimerCount <= TotalCount)
    {
	const FVector Location = GetActorLocation() + FVector(FMath::FRandRange(200.0f, 1000.0f), FMath::FRandRange(200.0f, 1000.0f), 0.0f);
	const FRotator Rotatiton = FRotator::ZeroRotator;
	AMyActor* SpawnObject = GetWorld()->SpawnActor<AMyActor>(CppClass, Location, Rotatiton);

	if (SpawnObject)
	{
	    SpawnedObjects.Add(SpawnObject);
	}
	}
	else
	{
	    GetWorldTimerManager().ClearTimer(SpawnTimerHandle);
	    for (int i = TotalCount; i >= 1; i--)
	    {
		GetWorldTimerManager().SetTimer(DestroyTimerHandle, this, &ACppHubActor::onTimeToDestroy, DestroyTimerRate, true);
	    }
	}
    
}

void ACppHubActor::onTimeToDestroy()
{
    if (!SpawnedObjects.IsEmpty())
    {
	SpawnedObjects.Top()->Destroy();
	SpawnedObjects.Pop();
    }
    else
    {
	GetWorldTimerManager().ClearTimer(DestroyTimerHandle);
    }
}